# Generated by Django 4.0.6 on 2022-07-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_application_appprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='AppProcess',
            field=models.CharField(choices=[('RA', 'Registration Approved'), ('UP', 'Under Process '), ('AP', 'Approved')], default='Registration Approved', max_length=100, null=True),
        ),
    ]
