# Generated by Django 4.0.6 on 2022-07-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_alter_application_appprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='AppProcess',
            field=models.CharField(choices=[('Registration Approved', 'RA'), ('Under Process ', 'UP'), ('Approved', 'AP')], default='Registration Approved', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='incubationtype',
            field=models.CharField(choices=[('Physical Incubation', 'PI'), ('Virtual Incubation ', 'VI')], max_length=100),
        ),
    ]
