# Generated by Django 4.0.6 on 2022-07-25 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_application_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
    ]
