# Generated by Django 4.0.6 on 2022-07-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_remove_application_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='AppProcess',
            field=models.CharField(choices=[('Registration Approved', 'Registration Approved'), ('Under Process ', 'Under Process'), ('Approved', 'Approved')], default='Registration Approved', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='incubationtype',
            field=models.CharField(choices=[('Physical Incubation', 'Physical Incubation'), ('Virtual Incubation ', 'Virtual Incubation')], max_length=100),
        ),
    ]
